# Node.js 이미지를 베이스로 사용합니다.
FROM node:16 as build

# 작업 디렉토리를 설정합니다.
WORKDIR /app

# package.json과 package-lock.json 파일을 복사합니다.
COPY package*.json ./

# 의존성 패키지를 설치합니다.
RUN npm install

# 소스 코드를 복사합니다.
COPY . .

# 애플리케이션을 빌드합니다.
RUN npm run build
